### ISSUE TITLE
Copyright notice?

### ISSUE THREAD

**Issue by PeeHaa** [voku/email-check#2]
It looks like you have taken Michael Rushton's regex pattern as [used in PHP](http://lxr.php.net/xref/PHP_5_4/ext/filter/logical_filters.c#529), but you forgot to add the[ copyright notice](http://lxr.php.net/xref/PHP_5_4/ext/filter/logical_filters.c#505)?

> ```
>  * Michael's regex carries this copyright:
> ```
> 
> 523     *
> 524     \* Copyright © Michael Rushton 2009-10
> 525     \* http://squiloople.com/
> 526     \* Feel free to use and redistribute this code. But please keep this copyright notice.

**Comment by voku** [comment]
thx for the feedback -> fixed -> https://github.com/voku/email-check/commit/cb0ba41126bc79334745ae0607b721579bc1f8af
