### ISSUE TITLE
DNS error check only MX Record ?

### ISSUE THREAD

**Issue by pbatroff** [voku/email-check#8]
Wouldn't it be a viable case for a valid email with a correct MX record, but no A-record? Email will be received that way. 

It's an edge case, but wouldn't it be more correct to change 
`return !\checkdnsrr($domain . '.', 'MX') || !\checkdnsrr($domain, 'A');`
to 
`return !\checkdnsrr($domain . '.', 'MX');`

in the [code here](https://github.com/voku/email-check/blob/2ee1ef4e9504c23ca8ea22b58f882dab08faea0f/src/voku/helper/EmailCheck.php#L251) ?

**Comment by voku** [comment]
Thanks for the bug-report ... and yep, I think you are right and it's fixed in version 3.0.1 -> see https://github.com/voku/email-check/commit/2acff4fcffe0bd49de8d55a414c3dc6f7498fcb9#diff-9bf7e6c7e7ec373eb21aeb4f55a2a020R254
